const fs = require('fs');
const path = require('path');

const csvPath = path.join(__dirname, '../catalog.csv');
const outputPath = path.join(__dirname, '../src/data/products.js');

function parseCSVLine(line) {
  const result = [];
  let current = '';
  let inQuotes = false;
  
  for (let i = 0; i < line.length; i++) {
    const char = line[i];
    if (char === '"') {
      if (inQuotes && line[i + 1] === '"') {
        current += '"';
        i++;
      } else {
        inQuotes = !inQuotes;
      }
    } else if (char === ',' && !inQuotes) {
      result.push(current.trim());
      current = '';
    } else {
      current += char;
    }
  }
  result.push(current.trim());
  return result;
}

function slugify(text) {
  return text
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, '-')
    .replace(/(^-|-$)/g, '');
}

try {
  if (!fs.existsSync(csvPath)) {
    console.error(`Error: catalog.csv not found at ${csvPath}`);
    process.exit(1);
  }

  const fileContent = fs.readFileSync(csvPath, 'utf8');
  // Handle carriage returns and split by lines
  const lines = fileContent.split(/\r?\n/).filter(line => line.trim() !== '');
  
  if (lines.length < 2) {
    console.error("Error: catalog.csv must contain a header row and at least one product row.");
    process.exit(1);
  }

  const headers = parseCSVLine(lines[0]);
  const products = [];

  for (let idx = 1; idx < lines.length; idx++) {
    const cells = parseCSVLine(lines[idx]);
    if (cells.length < 5) {
      // Skip empty or malformed lines
      continue;
    }

    const row = {};
    headers.forEach((header, i) => {
      row[header] = cells[i] || '';
    });

    // Parse Image list (separated by |)
    const imageList = row.image ? row.image.split('|').map(img => img.trim()) : [];

    const product = {
      id: row.id || slugify(row.name),
      slug: row.slug || row.id || slugify(row.name),
      name: row.name,
      price: parseInt(row.price || '0', 10),
      category: row.category,
      description: row.description,
      image: imageList[0] || '',
      images: imageList,
      recommended: row.recommended ? row.recommended.toLowerCase() === 'true' : false,
      collection: row.collection || '',
      
      // New Schema Fields
      tags: row.tags ? row.tags.split(',').map(t => t.trim()).filter(t => t !== '') : [],
      sku: row.sku || row.id || slugify(row.name),
      stock: row.stock ? parseInt(row.stock, 10) : -1,
      weight: row.weight ? parseInt(row.weight, 10) : 0,
      meta_title: row.meta_title || row.name,
      meta_description: row.meta_description || row.description?.slice(0, 155),
      instagram_url: row.instagram_url || ''
    };

    // Parse Specifications (Format: Key: Value | Key2: Value2)
    if (row.specifications && row.specifications.trim() !== '') {
      product.specifications = row.specifications.split('|').map(specStr => {
        const parts = specStr.split(':');
        const name = parts[0] ? parts[0].trim() : '';
        const value = parts.slice(1).join(':') ? parts.slice(1).join(':').trim() : '';
        return { name, value };
      }).filter(s => s.name !== '');
    }

    // Parse FAQs (Format: Q: Ques? | A: Ans. || Q: Ques2? | A: Ans2.)
    if (row.faqs && row.faqs.trim() !== '') {
      product.faqs = row.faqs.split('||').map(faqStr => {
        const parts = faqStr.split('|');
        const q = parts[0] ? parts[0].replace(/^(Q:)?\s*/i, '').trim() : '';
        const a = parts.slice(1).join('|') ? parts.slice(1).join('|').replace(/^(A:)?\s*/i, '').trim() : '';
        return { q, a };
      }).filter(f => f.q !== '');
    }

    // Parse Varieties (Format: Select Size | 4x4 Size:249 | 4x6 Size:349)
    if (row.varieties && row.varieties.trim() !== '') {
      const parts = row.varieties.split('|');
      const label = parts[0] ? parts[0].trim() : 'Select Option';
      const options = parts.slice(1).map((optStr, index) => {
        const subparts = optStr.split(':');
        const name = subparts[0] ? subparts[0].trim() : '';
        const price = subparts[1] ? parseInt(subparts[1].trim(), 10) : product.price;
        return {
          id: slugify(name),
          name,
          price,
          isDefault: index === 0
        };
      }).filter(o => o.name !== '');

      if (options.length > 0) {
        product.varieties = { label, options };
      }
    }

    products.push(product);
  }

  const jsContent = `// This file is auto-generated by scripts/parse-catalog.js. Do not edit directly.
export const products = ${JSON.stringify(products, null, 2)};
`;

  fs.writeFileSync(outputPath, jsContent, 'utf8');
  console.log(`Successfully generated products.js with ${products.length} catalog items.`);
} catch (err) {
  console.error("Error parsing catalog.csv:", err.message);
  process.exit(1);
}
